dist: bionic
# sudo: required
osx_image: xcode11
language: java

os:
  - linux
  - osx

env:
  - V=2.0.0

before_install:
  - OS=linux
  - ARCH=x86_64
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - bazel --bazelrc=./bazel.travis.rc build --keep_going //tests/...
  - bazel --bazelrc=./bazel.travis.rc test --keep_going //tests/...
