local_repository(
    name = "rules_iota",
    path = "..",
)

load("@rules_iota//:defs.bzl", "iota_deps")

iota_deps()

load("@prometheus_cpp//:repositories.bzl", "prometheus_cpp_repositories")

prometheus_cpp_repositories()
